# Generated by Django 5.1.6 on 2025-04-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
