# Generated by Django 5.1.6 on 2025-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_no',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('token_no', 'vendor')},
        ),
    ]
