# Generated by Django 5.1.7 on 2025-04-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_adminoutlet_vendor_location_id_vendor_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='ads',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='menus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
