# Generated by Django 5.1.7 on 2025-04-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='order',
        ),
        migrations.AddField(
            model_name='feedback',
            name='vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
