# Generated by Django 5.1.7 on 2025-04-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_remove_feedback_order_feedback_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, choices=[('dish', 'Dish'), ('service', 'Service')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('compliment', 'Compliment')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='want_to_reach_us',
            field=models.BooleanField(default=False),
        ),
    ]
