# Generated by Django 5.1.7 on 2025-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_feedback_category_feedback_feedback_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, choices=[('dish', 'Dish'), ('service', 'Service')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('compliment', 'Compliment')], max_length=10, null=True),
        ),
    ]
