# Generated by Django 5.1.6 on 2025-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_order_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shown_on_tv',
            field=models.BooleanField(default=False),
        ),
    ]
