# Generated by Django 5.1.6 on 2025-05-14 11:51

from django.db import migrations, models

def copy_old_fields_to_new_fields(apps, schema_editor):
    AdminOutlet = apps.get_model('vendors', 'AdminOutlet')
    for outlet in AdminOutlet.objects.all():
        if outlet.name and not outlet.customer_name:
            outlet.customer_name = outlet.name
        if outlet.email and not outlet.customer_email:
            outlet.customer_email = outlet.email
        if outlet.phone and not outlet.customer_contact:
            outlet.customer_contact = outlet.phone
        if outlet.address and not outlet.customer_address:
            outlet.customer_address = outlet.address
        if outlet.phone and not outlet.phone_number:
            outlet.phone_number = outlet.phone
        outlet.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_order_shown_on_tv'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminoutlet',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='customer_address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='customer_contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='customer_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.RunPython(copy_old_fields_to_new_fields),
    ]
