# Generated by Django 5.1.6 on 2025-05-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_adminoutlet_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminoutlet',
            name='address',
        ),
        migrations.RemoveField(
            model_name='adminoutlet',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminoutlet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminoutlet',
            name='phone',
        ),
    ]
