# Generated by Django 5.1.6 on 2025-05-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_adminoutlet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminoutlet',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adminoutlet',
            name='username',
        ),
    ]
