# Generated by Django 5.1.6 on 2025-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_remove_adminoutlet_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminoutlet',
            name='android_apk_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='android_tv_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='authentication_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='keypad_device_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='led_display_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='locations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='outlet_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='product_from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='product_registration_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='product_to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='project_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='total_count',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminoutlet',
            name='web_login_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
