# Generated by Django 5.1.6 on 2025-05-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_androiddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='androiddevice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
