# Generated by Django 5.1.6 on 2025-05-22 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_androiddevice_customer_androiddevice_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
