# Generated by Django 5.1.6 on 2025-05-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_alter_order_token_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='location_id',
            field=models.CharField(max_length=20),
        ),
    ]
