# Generated by Django 5.1.6 on 2025-05-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_alter_vendor_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androiddevice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
