# Generated by Django 5.1.6 on 2025-05-26 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0022_alter_androiddevice_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.adminoutlet'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_no',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='vendors.vendor'),
        ),
    ]
