# Generated by Django 5.1.6 on 2025-05-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_rename_customer_device_admin_outlet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='androiddevice',
            old_name='customer',
            new_name='admin_outlet',
        ),
    ]
