# Generated by Django 5.1.6 on 2025-05-28 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0025_rename_customer_androiddevice_admin_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
