# Generated by Django 5.1.6 on 2025-06-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0028_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='alias_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
