# Generated by Django 5.1.6 on 2025-06-19 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0029_vendor_alias_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androiddevice',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='android_devices', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='device',
            name='admin_outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='vendors.adminoutlet'),
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='vendors.vendor')),
            ],
        ),
    ]
