# Generated by Django 5.1.6 on 2025-06-19 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0030_alter_androiddevice_vendor_alter_device_admin_outlet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementimage',
            name='vendor',
        ),
        migrations.AddField(
            model_name='advertisementimage',
            name='admin_outlet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='vendors.adminoutlet'),
            preserve_default=False,
        ),
    ]
