# Generated by Django 5.1.6 on 2025-06-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0031_remove_advertisementimage_vendor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisementImage',
        ),
    ]
