# Generated by Django 5.1.6 on 2025-06-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0032_delete_advertisementimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('admin_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='vendors.adminoutlet')),
            ],
        ),
    ]
