# Generated by Django 5.1.6 on 2025-06-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0033_advertisementimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('days_active', models.JSONField(blank=True, default=list, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(blank=True, related_name='profiles', to='vendors.advertisementimage')),
            ],
        ),
    ]
