# Generated by Django 5.1.6 on 2025-06-20 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0034_advertisementprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementprofile',
            name='admin_outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_profiles', to='vendors.adminoutlet'),
        ),
    ]
