# Generated by Django 5.1.6 on 2025-06-24 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0036_alter_advertisementprofile_admin_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementProfileAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vendors', to='vendors.advertisementprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_profiles', to='vendors.vendor')),
            ],
            options={
                'unique_together': {('profile', 'vendor')},
            },
        ),
    ]
