# Generated by Django 5.1.6 on 2025-06-30 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0037_advertisementprofileassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminoutlet',
            name='auto_delete_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Set after how many hours orders should be auto-deleted (min 2 hours)', null=True),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='android_devices', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vendors.device'),
        ),
    ]
