# Generated by Django 5.1.6 on 2025-06-30 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0038_adminoutlet_auto_delete_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_order_id', models.IntegerField()),
                ('token_no', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('counter_no', models.IntegerField()),
                ('shown_on_tv', models.BooleanField()),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor')),
            ],
        ),
    ]
