# Generated by Django 5.1.6 on 2025-07-08 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0039_archivedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedorder',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.device'),
        ),
        migrations.AlterField(
            model_name='androiddevice',
            name='admin_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='android_device', to='vendors.adminoutlet'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_orders', to='vendors.device'),
        ),
    ]
