# Generated by Django 5.1.6 on 2025-07-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0040_archivedorder_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated_by',
            field=models.CharField(choices=[('keypad_device', 'Keypad Device'), ('customer', 'Customer'), ('manager', 'Manager'), ('admin', 'Admin')], default='keypad_device', max_length=20),
        ),
    ]
