# Generated by Django 5.1.6 on 2025-07-14 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0041_alter_order_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager (Android APK)'), ('web', 'Web User')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='vendors.adminoutlet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_role', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='vendors.vendor')),
            ],
        ),
    ]
