# Generated by Django 5.1.6 on 2025-07-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0043_archivedorder_user_profile_order_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='androiddevice',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile_devices', to='vendors.userprofile'),
        ),
    ]
