# Generated by Django 5.1.6 on 2025-07-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0044_androiddevice_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androiddevice',
            name='user_profile',
        ),
    ]
