# Generated by Django 5.1.6 on 2025-07-15 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0045_remove_androiddevice_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidAPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_outlet_apks', to='vendors.adminoutlet')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile_devices', to='vendors.userprofile')),
            ],
        ),
    ]
