# Generated by Django 5.1.6 on 2025-07-18 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0052_alter_order_unique_together_order_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedorder',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
