# Generated by Django 5.1.6 on 2025-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0054_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_send',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
