# Generated by Django 5.1.6 on 2025-08-08 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0056_alter_chatmessage_is_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_display_limit', models.PositiveIntegerField(default=8)),
                ('mqtt_mode', models.CharField(choices=[('broadcast', 'Broadcast to all TVs'), ('individual', 'Individual TV data'), ('keypad', 'Keypad-controlled TVs')], default='broadcast', max_length=20)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='vendors.vendor')),
            ],
        ),
    ]
