# Generated by Django 5.1.6 on 2025-08-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0057_vendorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='business_day_start_hour',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
