# Generated by Django 5.1.6 on 2025-08-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0058_vendorconfig_business_day_start_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorconfig',
            name='business_day_start_hour',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
