# Generated by Django 5.1.6 on 2025-08-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0059_alter_vendorconfig_business_day_start_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for MQTT server', max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=1883)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('qos', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='vendorconfig',
            name='mqtt_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.mqttserverconfig'),
        ),
    ]
