# Generated by Django 5.1.6 on 2025-08-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0060_mqttserverconfig_vendorconfig_mqtt_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorconfig',
            name='mqtt_server',
        ),
    ]
