# Generated by Django 5.1.6 on 2025-08-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0062_adminoutlet_mqtt_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoutlet',
            name='mqtt_server',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_outlets', to='vendors.mqttserverconfig'),
        ),
    ]
