# Generated by Django 5.1.6 on 2025-08-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0064_vendorconfig_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorconfig',
            name='mqtt_mode',
            field=models.CharField(choices=[('All', 'Broadcast to all TVs'), ('Individual', 'Individual TV data')], default='broadcast', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('token_no', 'vendor')},
        ),
    ]
