# Generated by Django 5.1.6 on 2025-08-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0065_alter_vendorconfig_mqtt_mode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
