# Generated by Django 5.1.6 on 2025-08-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0066_alter_order_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttserverconfig',
            name='tls',
            field=models.BooleanField(default=False, help_text='Use TLS for secure connection'),
        ),
    ]
