# Generated by Django 5.1.6 on 2025-08-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0067_mqttserverconfig_tls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorconfig',
            name='mqtt_mode',
            field=models.CharField(choices=[('All', 'Broadcast to all TVs'), ('Individual', 'Individual TV data')], default='All', max_length=20),
        ),
    ]
