# Generated by Django 5.1.6 on 2025-08-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0068_alter_vendorconfig_mqtt_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='tv_communication_mode',
            field=models.CharField(choices=[('MQTT', 'MQTT'), ('Firebase', 'Firebase')], default='MQTT', max_length=20),
        ),
    ]
