# Generated by Django 5.1.6 on 2025-08-22 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0069_vendorconfig_tv_communication_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='mqtt_server',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_configs', to='vendors.mqttserverconfig'),
        ),
    ]
