# Generated by Django 5.1.6 on 2025-08-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0070_vendorconfig_mqtt_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminoutlet',
            name='mqtt_server',
        ),
    ]
