# Generated by Django 5.1.6 on 2025-08-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0071_remove_adminoutlet_mqtt_server'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='androidapk',
            unique_together={('mac_address', 'user_profile')},
        ),
    ]
