# Generated by Django 5.1.6 on 2025-09-09 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0072_alter_androidapk_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_no', models.IntegerField(blank=True, null=True)),
                ('sender', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('chat', 'Chat'), ('status', 'Order Status'), ('offer', 'Offer'), ('info', 'Info')], default='chat', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_send', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='vendors.pushsubscription')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='vendors.vendor')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['vendor', 'timestamp'], name='vendors_web_vendor__afc8e1_idx')],
            },
        ),
    ]
