# Generated by Django 5.1.6 on 2025-09-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0073_webchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webchatmessage',
            name='type',
            field=models.CharField(default='chat', max_length=20),
        ),
    ]
