# Generated by Django 5.1.6 on 2025-09-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0074_alter_webchatmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androiddevice',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
