# Generated by Django 5.1.6 on 2025-09-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0076_webchatmessage_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebChatMessage',
        ),
    ]
