# Generated by Django 5.1.6 on 2025-09-10 03:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0077_delete_webchatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_no', models.IntegerField(blank=True, null=True)),
                ('sender', models.CharField(max_length=20)),
                ('type', models.CharField(default='chat', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_send', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='vendors.pushsubscription')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='vendors.vendor')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['vendor', 'timestamp'], name='vendors_web_vendor__afc8e1_idx')],
            },
        ),
    ]
