# Generated by Django 5.1.6 on 2025-09-10 06:23

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0078_webchatmessage'), 
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE vendors_webchatmessage
                MODIFY text LONGTEXT
                CHARACTER SET utf8mb4
                COLLATE utf8mb4_unicode_ci;
            """,
            reverse_sql="""
                ALTER TABLE vendors_webchatmessage
                MODIFY text LONGTEXT
                CHARACTER SET utf8
                COLLATE utf8_general_ci;
            """,
        ),
    ]
