# Generated by Django 5.1.6 on 2025-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0079_alter_webchatmessage_text_charset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webchatmessage',
            name='text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
