# Generated by Django 5.1.6 on 2025-09-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0080_alter_webchatmessage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorconfig',
            name='tv_communication_mode',
            field=models.CharField(choices=[('MQTT', 'MQTT'), ('Firebase', 'Firebase'), ('AZURE_IOT', 'Azure IoT Hub')], default='MQTT', max_length=20),
        ),
    ]
