# Generated by Django 5.1.6 on 2025-09-18 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0081_alter_vendorconfig_tv_communication_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('primary_key', models.TextField()),
                ('secondary_key', models.TextField()),
                ('primary_connection_string', models.TextField()),
                ('secondary_connection_string', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('android_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iot_credentials', to='vendors.androiddevice')),
            ],
        ),
    ]
