# Generated by Django 5.1.6 on 2025-09-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0082_iotdevicecredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevicecredential',
            name='primary_key',
        ),
        migrations.RemoveField(
            model_name='iotdevicecredential',
            name='secondary_key',
        ),
    ]
