# Generated by Django 5.1.6 on 2025-09-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0083_remove_iotdevicecredential_primary_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevicecredential',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_device_credentials', to='vendors.vendor'),
        ),
    ]
