# Generated by Django 5.1.6 on 2025-09-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0084_iotdevicecredential_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttserverconfig',
            name='password',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='mqttserverconfig',
            name='username',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
