# Generated by Django 5.1.6 on 2025-09-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0085_alter_mqttserverconfig_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='business_day_start_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
