# Generated by Django 5.1.6 on 2025-09-26 04:34

from django.db import migrations
import datetime


def copy_hour_to_time(apps, schema_editor):
    VendorConfig = apps.get_model("vendors", "VendorConfig")
    for vc in VendorConfig.objects.all():
        if vc.business_day_start_hour is not None:
            vc.business_day_start_time = datetime.time(
                hour=vc.business_day_start_hour,
                minute=0,
                second=0
            )
            vc.save(update_fields=["business_day_start_time"])


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0086_vendorconfig_business_day_start_time'),
    ]

    operations = [
        migrations.RunPython(copy_hour_to_time, reverse_code=migrations.RunPython.noop),
    ]
