# Generated by Django 5.1.6 on 2025-09-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0087_migrate_start_hour_to_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorconfig',
            name='business_day_start_time',
        ),
        migrations.AlterField(
            model_name='vendorconfig',
            name='business_day_start_hour',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
