# Generated by Django 5.1.6 on 2025-09-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0088_remove_vendorconfig_business_day_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorconfig',
            name='business_day_start_hour',
        ),
    ]
