# Generated by Django 5.1.6 on 2025-09-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0089_remove_vendorconfig_business_day_start_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='business_day_start_hour',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
