# Generated by Django 5.1.6 on 2025-09-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0090_vendorconfig_business_day_start_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorconfig',
            name='business_day_start_hour',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
