# Generated by Django 5.1.6 on 2025-09-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0091_alter_vendorconfig_business_day_start_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorconfig',
            name='tv_communication_mode',
            field=models.CharField(choices=[('MQTT', 'Model 1(M)'), ('Firebase', 'Model 2(F)'), ('AZURE_IOT', 'Model 3(A)')], default='MQTT', max_length=20),
        ),
    ]
