# Generated by Django 5.1.6 on 2025-09-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0092_alter_vendorconfig_tv_communication_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoutlet',
            name='authentication_status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
