# Generated by Django 5.1.6 on 2025-09-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0093_alter_adminoutlet_authentication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoutlet',
            name='authentication_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
