# Generated by Django 5.1.6 on 2025-10-07 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0094_alter_adminoutlet_authentication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready'), ('created', 'Created'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='preparing', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('preparing', 'Preparing'), ('ready', 'Ready'), ('created', 'Created'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready'), ('created', 'Created'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], max_length=20)),
                ('changed_by', models.CharField(choices=[('keypad_device', 'Keypad Device'), ('customer', 'Customer'), ('manager', 'Manager'), ('admin', 'Admin')], default='manager', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='vendors.order')),
            ],
        ),
    ]
