# Generated by Django 5.1.6 on 2025-10-09 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0095_alter_order_status_orderstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField()),
                ('archived_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='vendors.archivedorder')),
            ],
        ),
    ]
