# Generated by Django 5.1.6 on 2025-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0096_archivedorderstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedorderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
