# Generated by Django 5.1.6 on 2025-10-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0097_alter_archivedorderstatushistory_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementimage',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
