# Generated by Django 5.1.6 on 2025-10-13 10:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0099_update_chatmessage_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='auto_delete_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Set after how many hours orders should be auto-deleted (min 2 hours)', null=True),
        ),
        migrations.AddField(
            model_name='vendorconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='webchatmessage',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
