# Generated by Django 5.1.6 on 2025-10-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0100_vendorconfig_auto_delete_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='vendors.advertisementprofile')),
            ],
        ),
    ]
