# Generated by Django 5.1.6 on 2025-10-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0101_advertisementslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminoutlet',
            name='auto_delete_hours',
        ),
    ]
