# Generated by Django 5.1.6 on 2025-10-29 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0102_remove_adminoutlet_auto_delete_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorconfig',
            name='mqtt_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_configs', to='vendors.mqttserverconfig'),
        ),
    ]
