# Generated by Django 5.1.6 on 2025-10-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0103_alter_vendorconfig_mqtt_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='flight_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pnr_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seat_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sequence_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('boarding_started', 'Boarding Started'), ('boarding_closed', 'Boarding Closed'), ('departed', 'Departed'), ('cancelled', 'Cancelled')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('boarding_started', 'Boarding Started'), ('boarding_closed', 'Boarding Closed'), ('departed', 'Departed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('boarding_started', 'Boarding Started'), ('boarding_closed', 'Boarding Closed'), ('departed', 'Departed'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendor', 'token_no'], name='vendors_ord_vendor__a8410f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sequence_code'], name='vendors_ord_sequenc_537b08_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['flight_no', 'pnr_no'], name='vendors_ord_flight__0f24f8_idx'),
        ),
    ]
