# Generated by Django 5.1.6 on 2025-10-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0104_alter_order_options_order_flight_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webchatmessage',
            name='sequence_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('boarding', 'Boarding'), ('final_call', 'Proceed to Aircraft'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('boarding', 'Boarding'), ('final_call', 'Proceed to Aircraft'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('boarding', 'Boarding'), ('final_call', 'Proceed to Aircraft'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
