# Generated by Django 5.1.6 on 2025-10-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0105_webchatmessage_sequence_code_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webchatmessage',
            name='sequence_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
