# Generated by Django 5.1.6 on 2025-10-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0106_alter_webchatmessage_sequence_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sequence_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
