# Generated by Django 5.1.6 on 2025-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0107_chatmessage_sequence_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
