# Generated by Django 5.1.6 on 2025-11-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0108_order_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sequence_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
