# Generated by Django 5.1.6 on 2025-11-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0109_alter_order_sequence_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorconfig',
            name='business_day_start_hour',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
