# Generated by Django 5.1.6 on 2025-11-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0110_alter_vendorconfig_business_day_start_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='last_checked_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='last_push_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='last_push_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('stale', 'Stale'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('bp_issued', 'B.Pass Issued'), ('checked_in', 'Checked-In'), ('boarding_shortly', 'Boarding Shortly'), ('boarding_announced', 'Boarding Announced'), ('gate_change', 'Gate Change'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('bp_issued', 'B.Pass Issued'), ('checked_in', 'Checked-In'), ('boarding_shortly', 'Boarding Shortly'), ('boarding_announced', 'Boarding Announced'), ('gate_change', 'Gate Change'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('bp_issued', 'B.Pass Issued'), ('checked_in', 'Checked-In'), ('boarding_shortly', 'Boarding Shortly'), ('boarding_announced', 'Boarding Announced'), ('gate_change', 'Gate Change'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
