# Generated by Django 5.1.6 on 2025-11-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0111_pushsubscription_last_checked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('bp_issued', 'B.Pass Issued'), ('checked_in', 'Checked-In'), ('boarding_shortly', 'Boarding Shortly'), ('boarding_announced', 'Boarding Announced'), ('gate_change', 'Gate Change'), ('rescheduled', 'Rescheduled'), ('flightcancel', 'Cancelled')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('bp_issued', 'B.Pass Issued'), ('checked_in', 'Checked-In'), ('boarding_shortly', 'Boarding Shortly'), ('boarding_announced', 'Boarding Announced'), ('gate_change', 'Gate Change'), ('rescheduled', 'Rescheduled'), ('flightcancel', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('bp_issued', 'B.Pass Issued'), ('checked_in', 'Checked-In'), ('boarding_shortly', 'Boarding Shortly'), ('boarding_announced', 'Boarding Announced'), ('gate_change', 'Gate Change'), ('rescheduled', 'Rescheduled'), ('flightcancel', 'Cancelled')], max_length=20, null=True),
        ),
    ]
