# Generated by Django 5.1.6 on 2025-11-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0112_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='no_of_packs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], max_length=20, null=True),
        ),
    ]
