# Generated by Django 5.1.6 on 2025-11-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0113_order_customer_name_order_no_of_packs_order_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivedorder',
            name='no_of_packs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
