# Generated by Django 5.1.6 on 2025-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0114_archivedorder_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='processing_time_seconds',
            field=models.IntegerField(blank=True, help_text='Duration spent in previous status before this update.', null=True),
        ),
    ]
