# Generated by Django 5.1.6 on 2025-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0115_orderstatushistory_processing_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='use_utilities',
            field=models.BooleanField(default=False),
        ),
    ]
