# Generated by Django 5.1.6 on 2025-11-21 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0116_vendorconfig_use_utilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_name', models.CharField(help_text='Internal name used within the system', max_length=100)),
                ('alias_name', models.CharField(help_text='Display name shown to customers', max_length=100)),
                ('token_mode', models.CharField(choices=[('continuous', 'Continuous'), ('utility_specific', 'Utility Specific')], default='continuous', help_text='Controls token numbering behaviour', max_length=20)),
                ('prefix', models.CharField(blank=True, help_text='3-character prefix (e.g., ROM, VIP, OUT)', max_length=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='vendors.vendor')),
            ],
        ),
    ]
