# Generated by Django 5.1.6 on 2025-11-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0117_utility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utility',
            old_name='alias_name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='utility',
            name='display_code',
            field=models.CharField(default=None, help_text='Short code used for UI display (e.g., AC, GD, VIP)', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utility',
            name='utility_name',
            field=models.CharField(help_text='Display name shown to system', max_length=100),
        ),
    ]
