# Generated by Django 5.1.6 on 2025-11-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0118_rename_alias_name_utility_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVDeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_qr', models.BooleanField(default=False)),
                ('qr_alignment', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10)),
                ('bookings_visible_count', models.PositiveSmallIntegerField(default=3)),
                ('name', models.BooleanField(default=True)),
                ('phone_no', models.BooleanField(default=True)),
                ('packs', models.BooleanField(default=True)),
                ('date_time', models.BooleanField(default=True)),
                ('token_no', models.BooleanField(default=True)),
                ('utility_key_type', models.CharField(choices=[('utility_name', 'Utility Name'), ('display_name', 'Display Name'), ('display_code', 'Display Code')], default='display_name', max_length=20)),
                ('screen_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='landscape', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tv_config', to='vendors.androiddevice')),
                ('utilities', models.ManyToManyField(blank=True, related_name='tv_display_configs', to='vendors.utility')),
            ],
        ),
    ]
