# Generated by Django 5.1.6 on 2025-11-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0119_tvdeviceconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TVDeviceConfig',
        ),
    ]
