# Generated by Django 5.1.6 on 2025-11-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0120_delete_tvdeviceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVDeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_qr', models.BooleanField(default=False)),
                ('qr_alignment', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10)),
                ('items_to_show', models.PositiveSmallIntegerField(default=1)),
                ('booking_fields', models.JSONField(default=list)),
                ('utility_name_mode', models.CharField(choices=[('name', 'Utility Name'), ('display_name', 'Display Name'), ('display_code', 'Display Code')], max_length=20)),
                ('screen_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='landscape', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_device_configs', to='vendors.adminoutlet')),
                ('utilities', models.ManyToManyField(blank=True, related_name='tv_configs', to='vendors.utility')),
            ],
        ),
    ]
