# Generated by Django 5.1.6 on 2025-11-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0121_tvdeviceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='androiddevice',
            name='tv_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='vendors.tvdeviceconfig'),
        ),
    ]
