# Generated by Django 5.1.6 on 2025-11-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0123_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='vibration_duration',
            field=models.PositiveIntegerField(default=5, help_text='Vibration duration in seconds'),
        ),
        migrations.AddField(
            model_name='vendorconfig',
            name='vibration_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable vibration for customer notifications'),
        ),
        migrations.AddField(
            model_name='vendorconfig',
            name='vibration_pattern',
            field=models.CharField(default='alert_strong', help_text='Vibration pattern key for customer notification alerts', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Created'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tvdeviceconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='vendors_ord_created_43be9f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendor', '-created_at'], name='vendors_ord_vendor__18c28f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendor', 'created_date'], name='vendors_ord_vendor__bdfb73_idx'),
        ),
        migrations.AddIndex(
            model_name='tvdeviceconfig',
            index=models.Index(fields=['admin_outlet', '-created_at'], name='vendors_tvd_admin_o_bb3e8c_idx'),
        ),
    ]
