# Generated by Django 5.1.6 on 2025-11-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0124_vendorconfig_vibration_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_booking_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table_booking_no'], name='vendors_ord_table_b_026ba1_idx'),
        ),
    ]
