# Generated by Django 5.1.6 on 2025-11-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0125_order_table_booking_no_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoutlet',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='androiddevice',
            index=models.Index(fields=['mac_address', 'admin_outlet'], name='vendors_and_mac_add_8ad9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='androiddevice',
            index=models.Index(fields=['admin_outlet'], name='vendors_and_admin_o_b360bc_idx'),
        ),
        migrations.AddIndex(
            model_name='androiddevice',
            index=models.Index(fields=['mac_address'], name='vendors_and_mac_add_95ae9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='utility',
            constraint=models.UniqueConstraint(fields=('vendor', 'utility_name'), name='unique_utility_name_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='utility',
            constraint=models.UniqueConstraint(fields=('vendor', 'display_name'), name='unique_display_name_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='utility',
            constraint=models.UniqueConstraint(fields=('vendor', 'display_code'), name='unique_display_code_per_vendor'),
        ),
    ]
