# Generated by Django 5.1.6 on 2025-11-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0126_alter_adminoutlet_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='utility_booking_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorconfig',
            name='continuous_booking_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
