# Generated by Django 5.1.6 on 2025-12-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0127_utility_utility_booking_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='phone_number_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
