# Generated by Django 5.1.6 on 2025-12-01 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0128_vendorconfig_phone_number_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vendors.utility'),
        ),
    ]
