# Generated by Django 5.1.6 on 2025-12-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0129_order_utility'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webchatmessage',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
