# Generated by Django 5.1.6 on 2025-12-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0130_chatmessage_booking_id_webchatmessage_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='booking_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='webchatmessage',
            name='booking_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
