# Generated by Django 5.1.6 on 2025-12-08 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0131_chatmessage_booking_no_webchatmessage_booking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='new_utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_new_utility', to='vendors.utility'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='old_utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_old_utility', to='vendors.utility'),
        ),
    ]
