# Generated by Django 5.1.6 on 2025-12-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0132_orderstatushistory_new_utility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_orders', to='vendors.utility'),
        ),
    ]
