# Generated by Django 5.1.6 on 2025-12-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0133_order_current_utility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatushistory',
            old_name='old_utility',
            new_name='previous_utility',
        ),
    ]
