# Generated by Django 5.1.6 on 2025-12-11 07:25

import static.utils.functions.utils
from django.db import migrations, models


def set_default_closing_messages(apps, schema_editor):
    VendorConfig = apps.get_model('vendors', 'VendorConfig')
    get_default = static.utils.functions.utils.get_default_closing_message

    for config in VendorConfig.objects.all():
        if not config.closing_message:  # Only update empty values
            config.closing_message = get_default()
            config.save(update_fields=["closing_message"])


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0134_rename_old_utility_orderstatushistory_previous_utility'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='closing_message',
            field=models.TextField(
                default=static.utils.functions.utils.get_default_closing_message,
                help_text='Custom closing/thank you message'
            ),
        ),

        # 🔥 IMPORTANT: Fill existing rows with default
        migrations.RunPython(set_default_closing_messages, migrations.RunPython.noop),
    ]
