# Generated by Django 5.1.6 on 2025-12-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0136_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='utility',
            constraint=models.UniqueConstraint(fields=('vendor', 'prefix'), name='unique_prefix_per_vendor'),
        ),
    ]
