# Generated by Django 5.1.6 on 2025-12-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0137_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='prefix',
            field=models.CharField(blank=True, help_text='4-character prefix (e.g., ROM, VIP, OUT)', max_length=4, null=True),
        ),
    ]
