# Generated by Django 5.1.6 on 2025-12-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0138_alter_utility_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='config_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
