# Generated by Django 5.1.6 on 2026-03-23 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0139_tvdeviceconfig_config_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_utilities',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='vendors.utility'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('cancelled', 'Cancelled'), ('operation_closed', 'Close Operation')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Created'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('cancelled', 'Cancelled'), ('operation_closed', 'Close Operation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('cancelled', 'Cancelled'), ('operation_closed', 'Close Operation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager (Android APK)'), ('web', 'Web User'), ('utility_user', 'Utility User (Kitchen)')], max_length=20),
        ),
        migrations.CreateModel(
            name='BuffetOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='created', max_length=20)),
                ('customizations', models.JSONField(blank=True, default=list, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_grouped', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffet_items', to='vendors.order')),
                ('utility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buffet_ordered_items', to='vendors.utility')),
            ],
        ),
    ]
