# Generated by Django 5.1.6 on 2026-03-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0140_userprofile_assigned_utilities_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='vendors.utility')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('utility', 'name'), name='unique_option_name_per_utility')],
            },
        ),
    ]
