# Generated by Django 5.1.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0141_utilityoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webchatmessage",
            name="type",
            field=models.CharField(default="chat", max_length=48),
        ),
    ]
