# Generated by Django 5.1.6 on 2026-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0142_alter_webchatmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('system', 'System')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Created'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin_manager', 'Admin Manager'), ('outlet_manager', 'Outlet Manager'), ('order_manager', 'Order Manager'), ('manager', 'Manager (Android APK)'), ('web', 'Web User'), ('utility_user', 'Utility User (Kitchen)')], max_length=20),
        ),
    ]
