# Generated by Django 5.1.6 on 2026-04-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0144_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin_manager', 'Admin Manager'), ('outlet_manager', 'Outlet Manager'), ('order_manager', 'Order Manager'), ('manager', 'Manager (Android APK)'), ('web', 'Web User'), ('web_user', 'Web Manager'), ('utility_user', 'Utility User (Kitchen)'), ('airport_manager', 'Airport Manager'), ('outlet_staff', 'Outlet Staff')], max_length=20),
        ),
    ]
