# Generated by Django 5.1.6 on 2026-04-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0145_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='announcement_language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='audio_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='blink_token',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='blink_utility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='counter_font_size',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='counter_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='qr_base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='qr_placement',
            field=models.CharField(choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], default='bottom-right', max_length=20),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='show_customer_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='show_order_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='show_phone_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='token_font_size',
            field=models.CharField(default='large', max_length=20),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='token_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='utility_font_size',
            field=models.CharField(default='small', max_length=20),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='utility_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('created', 'Request Created'), ('waiting', 'Allocation Pending'), ('allocated', 'Allocated'), ('occupied', 'Occupied'), ('booking_cancelled', 'Booking Cancelled'), ('operation_closed', 'Close Operation')], max_length=20, null=True),
        ),
    ]
