# Generated by Django 5.1.6 on 2026-04-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0146_tvdeviceconfig_announcement_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvdeviceconfig',
            name='announcement_language',
            field=models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam')], default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='tvdeviceconfig',
            name='counter_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra-large', 'Extra Large')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvdeviceconfig',
            name='qr_base_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tvdeviceconfig',
            name='token_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra-large', 'Extra Large')], default='large', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvdeviceconfig',
            name='utility_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra-large', 'Extra Large')], default='small', max_length=20),
        ),
    ]
