# Generated by Django 5.1.6 on 2026-04-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0147_alter_tvdeviceconfig_announcement_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='display_columns',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tvdeviceconfig',
            name='display_rows',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
