# Generated by Django 5.1.6 on 2026-04-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0152_tvdeviceconfig_qr_expiry_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvadvertisement',
            options={'ordering': ['sequence', 'created_at', 'id']},
        ),
    ]
