# Generated by Django 5.1.6 on 2026-05-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0159_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapk',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
