from django.urls import path
from .import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('outlets/', views.outlets, name='outlets'),
    path('create_outlet/', views.create_outlet, name='create_outlet'),
    path('update_outlet/', views.update_outlet_page, name='update_outlet_page'),
    path('create_users/', views.create_users, name='create_users'), 
    path('user_list/', views.user_list, name='user_list'),
    path('manager_devices/',views.manager_devices,name='manager_devices'),
    path('keypad_devices/', views.keypad_devices, name='keypad_devices'),
    path('android_tvs/', views.android_tvs, name='android_tvs'),
    path('configurations/', views.configurations, name='configurations'),
    path('new_profile/', views.new_profile, name='new_profile'),
    path('profile_list/', views.profile_list, name='profile_list'),
    path('map_profiles/', views.map_profiles, name='map_profiles'), 
    path('mapped_list/', views.mapped_list, name='mapped_list'),
    path('banners/', views.banners, name='banners'), 
    path('configurations/', views.configurations, name='configurations'), 
    path('total_orders/', views.total_orders, name='total_orders'),
    path('order_details/', views.order_details, name='order_details'),
    path('api/create_vendor/', views.create_vendor, name='create_vendor'),
    path('api/update_vendor/', views.update_vendor, name='update_vendor'),
    path('api/create_user/', views.create_user, name='create_user'), 
    path('api/get_users/', views.get_users, name='get_users'), 
    path('api/get_manager_devices/',views.get_manager_devices,name='get_manager_devices'),
    path('api/get_vendors/', views.get_vendors, name='get_vendors'),
    path('api/get_devices/', views.get_devices, name='get_devices'),
    path('api/unmap_device/<int:device_id>/', views.unmap_device, name='unmap_device'),
    path('api/map_device/<int:device_id>/', views.map_device, name='map_device'),
    path('api/get_android_tvs/', views.get_android_tvs, name='get_android_tvs'),
    path('api/unmap_android_tvs/<int:device_id>/', views.unmap_android_tvs, name='unmap_android_tvs'),
    path('api/map_android_tvs/<int:device_id>/', views.map_android_tvs, name='map_android_tvs'),
    path('api/banner_upload/', views.upload_banner, name='upload_banner'),
    path('api/banner_list/', views.list_banners, name='list_banners'),
    path('api/banner_delete/', views.delete_banner, name='delete_banner'),
    path('api/create_ad_profile/', views.create_advertisement_profile, name='create_advertisement_profile'),
    path('api/get_ad_profiles/', views.get_advertisement_profiles, name='get_ad_profile'),
    path('api/delete_ad_profile/', views.delete_ad_profiles, name='delete_ad_profiles'),
    path('api/available_profiles/<int:vendor_id>/', views.get_available_profiles, name='available_profiles'),
    path('api/assign_ad_profile/', views.assign_ad_profile, name='assign_ad_profile'),
    path('api/assigned_profiles/', views.assigned_profiles, name='assigned_profiles'),
    path('api/unmap_profile/<int:vendor_id>/<int:profile_id>/', views.unmap_profile, name='unmap_profile'),
    path('api/get_vendor_details/', views.get_vendor_details, name='get_vendor_details'),
    path('api/get_outlet_creation_data/', views.get_outlet_creation_data, name='get_outlet_creation_data'),
    path('api/config/', views.config, name='config'), 
    path('api/order_counts_summary/', views.order_counts_summary, name='order_counts_summary'),
    path('api/filtered_orders/', views.filtered_orders, name='get_orders'),
    path('api/dashboard_metrics/', views.dashboard_metrics, name='dashboard_metrics'),  
]
 